---
max-line-length: 110

pylint:
  disable:
    - wrong-import-order
    - no-else-return
    - broad-except
    - unused-argument
    - missing-timeout # Default timeout set by c2cwsgiutils

mccabe:
  run: false
