inherits:
  - utils:base
  - utils:no-design-checks
  - utils:fix
  - duplicated

pylint:
  disable:
    - missing-timeout # Done by c2cwsgiutils

mypy:
  run: false

bandit:
  run: false

pyroma:
  run: false
