#!/bin/bash -eux

git config --global user.email "ci@camptocamp.com"
git config --global user.name "CI"

mkdir /repos
cd /repos

git init master
cd master
cat > shared_config_manager.yaml << END
sources:
  test_git:
    type: git
    repo: /repos/test_git
    tags: ['test']
    template_engines:
      - type: shell
        environment_variables: true
END
git add shared_config_manager.yaml
git commit --message="Initial commit"
cd ..

git init test_git
cd test_git
# shellcheck disable=SC2238
echo "Hello world" > test
git add test
git commit --message="Initial commit"
git tag 1.0.0
git tag otherTag
