version: '2'
services:
  api:
    image: camptocamp/shared_config_manager:latest
    environment: &scm_env
      STATS_VIEW: 1
      # STATSD_ADDRESS: 172.17.0.1:8125
      # STATSD_PREFIX: shared_config_manager.dev.app
      C2C_SECRET: toto
      LOG_LEVEL: DEBUG
      C2CWSGI_LOG_LEVEL: DEBUG
      OTHER_LOG_LEVEL: DEBUG
      C2C_REDIS_URL: redis://redis:6379
      DEVELOPMENT: 1
      COVERAGE: 1
      C2C_PROFILER_PATH: /app_profiler
      GUNICORN_PARAMS: '-b :8080 --reload'
      MASTER_CONFIG: &master_config |
        type: git
        key: changeme
        repo: /repos/master
    volumes:
      - /tmp/test_repos:/repos:rw
    links:
      - redis
    ports:
      - 8080:8080
    hostname: api

  slave:
    image: camptocamp/shared_config_manager:latest
    environment: *scm_env
    command: ['/app/shared_config_slave.py']
    volumes:
      - /tmp/test_repos:/repos:rw
    links:
      - redis
    hostname: slave

  redis:
    image: redis:4
    mem_limit: 64m
    ports:
      - 16379:6379
    command: redis-server --save "" --appendonly no
    user: www-data
