---
version: 2
updates:
  - package-ecosystem: docker
    directory: '/app'
    schedule:
      interval: weekly
      time: '02:00'
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: '02:00'
  - package-ecosystem: pip
    directory: "/app"
    schedule:
      interval: daily
      time: '02:00'
  - package-ecosystem: pip
    directory: "/acceptance_tests"
    schedule:
      interval: daily
      time: '02:00'
