# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/dependabot-2.0.json

version: 2
updates:
  - package-ecosystem: pip
    dependency-type: all
    directory: /
    ignore:
      - dependency-name: none
  - package-ecosystem: pip
    dependency-type: all
    directory: '/app'
    ignore:
      - dependency-name: none
  - package-ecosystem: pip
    dependency-type: all
    directory: '/acceptance_tests'
    ignore:
      - dependency-name: none

  - package-ecosystem: docker
    directory: /app
    schedule:
      interval: weekly
    ignore:
      - dependency-name: none
  - package-ecosystem: docker
    directory: '/acceptance_tests'
    schedule:
      interval: weekly
    ignore:
      - dependency-name: none
