# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/tag-publish/1.0.1/tag_publish/schema.json

docker:
  images:
    - name: camptocamp/shared_config_manager
dispatch:
  - {}
