---
strictness: veryhigh

max-line-length: 110

pylint:
  disable:
    - wrong-import-order
    - no-else-return
    - broad-except
    - raising-format-tuple
    - cyclic-import # check don't looks to work...

mccabe:
  run: false

mypy:
  run: true

bandit:
  run: true
