---
strictness: veryhigh

max-line-length: 110

pylint:
  disable:
    - too-many-locals
    - too-many-branches
    - too-many-arguments
    - too-many-instance-attributes
    - too-many-statements
    - too-few-public-methods
    - wrong-import-order
    - no-else-return
    - broad-except
    - raising-format-tuple
    - missing-timeout # Default timeout set by c2cwsgiutils

mccabe:
  run: false

mypy:
  run: true
