version:
  branch_to_version_re:
    - from: release_([0-9]+)
      to: \1
    - from: master
      to: '3'

checks:
  versions: False
  codespell: False
  isort: False
  black: False

publish:
  pypi:
    packages: []
