# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.0/c2cciutils/schema.json

version:
  branch_to_version_re:
    - from: release_([0-9]+)
      to: \1
    - from: master
      to: '3'

checks:
  versions: False
  codespell: False
  isort: False
  black: False
  required_workflows: False

publish:
  pypi:
    packages: []

audit:
  pipfile: false
  pipfile_lock: false
