version:
  branch_to_version_re:
    - from: release_([0-9]+)
      to: \1
    - from: master
      to: '3'

checks:
  required_workflows: False
  versions: false
  prettier: false

publish:
  pypi:
    packages: []

audit:
  snyk:
    no_install:
    - acceptance_tests/Pipfile
