version:
  branch_to_version_re:
    - from: release_([0-9]+)
      to: \1
    - from: master
      to: master

checks:
  required_workflows: False

publish:
  pypi:
    packages: []

audit:
  snyk:
    no_install:
      - acceptance_tests/Pipfile
