---
name: Audit

on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  main:
    runs-on: ubuntu-20.04
    name: Audit
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        branch:
          - release_2
          - release_3
          - '3.1'
          - '3.2'
          - master

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --pre c2cciutils

      - name: Audit
        run: c2cciutils-audit --branch=${{ matrix.branch }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
