name: Nightly

on:
  schedule:
    - cron: '45 3 * * *'

env:
  IN_CI: '1'
  SUMMON_PROVIDER: /usr/local/bin/gopass

jobs:
  rebuild:
    name: Nightly
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        branch:
          - release_1
          - release_2

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: pypi docker

      - run: |
          sudo rm /etc/apt/sources.list.d/*.list
          sudo apt update
          sudo apt install --yes python3-wheel

      - run: sudo python3 -m pip install --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      - name: Pull
        run: make pull

      - name: Build
        run: make build
        env:
          PRIVATE_SSH_KEY: ${{secrets.PRIVATE_SSH_KEY}}

      - name: Acceptance
        run: make acceptance
        env:
          PRIVATE_SSH_KEY: ${{secrets.PRIVATE_SSH_KEY}}

      - name: Publish
        run: c2cciutils-publish --type=rebuild --branch=${{github.ref}}
