---
name: Nightly

on:
  schedule:
    - cron: '45 3 * * *'

env:
  SUMMON_PROVIDER: /usr/local/bin/gopass

jobs:
  rebuild:
    name: Nightly
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        branch:
          - release_2
          - release_3
          - '3.1'
          - master

    steps:
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: 19.03
      - run: sudo python3 -m pip install docker-compose==1.28.4

      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: docker

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      - name: Pull
        run: make pull

      - name: Build
        run: make build
        env:
          PRIVATE_SSH_KEY: ${{secrets.PRIVATE_SSH_KEY}}

      - name: Acceptance
        run: make acceptance
        env:
          PRIVATE_SSH_KEY: ${{secrets.PRIVATE_SSH_KEY}}

      - name: Publish
        run: c2cciutils-publish --type=rebuild --branch=${{ matrix.branch }}
